name: Schema test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"


jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Installing all necessary packages
        run: pip install -r tests/schema_tests/requirements.txt
      - name: Run tests
        working-directory: ./tests/schema_tests
        run: python -m pytest -v
