name: Schema test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"


jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      # Runs positive Schemathesis tests
      - uses: schemathesis/action@v1
        with:
          # A local API schema location
          schema: ',/docs/swagger.json'
          # API base URL
          base-url: 'https://gridproxy.dev.grid.tf'
